// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn7uFFFJiHR8Nn0eFhkpu5NUJTD205lhI',
    appId: '1:537376924878:web:14f599d3f3268119049c9f',
    messagingSenderId: '537376924878',
    projectId: 'chat-app-84985',
    authDomain: 'chat-app-84985.firebaseapp.com',
    storageBucket: 'chat-app-84985.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzoWVekqrVnMwjqAScjM04RMZF5UJSezg',
    appId: '1:537376924878:android:6cd12f5737ea52a5049c9f',
    messagingSenderId: '537376924878',
    projectId: 'chat-app-84985',
    storageBucket: 'chat-app-84985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVBv_nc09b6OYKEvM8upKooSOSeOecqW4',
    appId: '1:537376924878:ios:f7a19c31d3da9634049c9f',
    messagingSenderId: '537376924878',
    projectId: 'chat-app-84985',
    storageBucket: 'chat-app-84985.appspot.com',
    iosBundleId: 'com.example.biddingApp',
  );
}
